Add labels
omnivector-solutions/charm-prometheus-node-exporter pull request #4
Opened 2021-08-02 14:58 UTC by heitorPB

**Please provide description of the purpose of this pull request, as well as its
motivation and context.**

Add  option for setting metrics labels.

Final checklist
- [x] I am the author of these changes, or I have the rights to submit them.
- [ ] I added the relevant changed to the README and/or documentation.
- [x] I self reviewed my own code.

2021-10-04 21:53 UTC, dusktreader requested changes

2021-10-04 21:53 UTC, dusktreader commented on src/charm.py
> +        labels = self.model.config.get("labels").replace('', '')
What does the `replace()` do here?

2022-05-12 13:04 UTC, heitorPB commented
This PR is ready for review, but upstream does not support labels yet...

2022-06-07 15:08 UTC, matheushent commented on .github/workflows/pull_request.yaml
> +                  sudo lxd init --auto
thinking out loud: we could implement an action for this

2023-08-04 20:22 UTC, closed without merging